### PR TITLE
Allow auth0 EU domains

### LINKED ISSUE #16: 0.1.4 does not work with .eu domains
User info comes through, but then a big error box is printed:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/app/deep_digest/app.py", line 12, in <module>
    user_info = login_button(settings.AUTH0_CLIENT_ID, domain=settings.AUTH0_DOMAIN)
  File "/usr/local/lib/python3.10/site-packages/auth0_component/__init__.py", line 82, in login_button
    elif isAuth(response = user_info, domain = domain):
  File "/usr/local/lib/python3.10/site-packages/auth0_component/__init__.py", line 89, in isAuth
    return getVerifiedSubFromToken(token = response['token'], domain=domain) == response['sub']
  File "/usr/local/lib/python3.10/site-packages/auth0_component/__init__.py", line 28, in getVerifiedSubFromToken
    raise ValueError
ValueError
domain should end with ".us.auth0.com" (no slash)
```

Problem is here:
https://github.com/conradbez/streamlit-auth0/blob/05c4d8708ecf332025821b5e1c2801d462e432f7/auth0_component/__init__.py#L26

### PR DESCRIPTION
**Pull request by grokpot**
Should fix #16 

@conradbez  Don't know how you test this locally - somehow you're using Vite?

### CODE REVIEW

**Review by abhishekpareek002 — APPROVED** [review]

**Comment by crivera** [comment]
with older applications there is actually no `us` or `eu`. can you just remove the check? or make it optional?

**Comment by jrvidotti** [comment]
I think this PR doesn't work with all auth0 regions. My domain is only mydomain.auth0.com, don't ask me why! :)

**Comment by juanmav** [comment]
> I think this PR doesn't work with all auth0 regions. My domain is only mydomain.auth0.com, don't ask me why! :)

If you check the code actually it does check that type of custom domain and supports eu as well.

I test this fix in my environment and works properly (at least for me)

@grokpot you saved me a lot of hours thanks!

**Comment by juanmav** [comment]
This is my monkey patch, I hope it helps!

```python
# Monkey patch the library
def patchGetVerifiedSubFromToken(token, domain):
    from six.moves.urllib.request import urlopen
    import re
    from jose import jwt
    import json
    domain = "https://"+domain
    if not re.match(r".*\.auth0\.com$", domain):
        print('domain should end with ".XX.auth0.com" (no trailing slash)')
        raise ValueError
    jsonurl = urlopen(domain+"/.well-known/jwks.json")
    jwks = json.loads(jsonurl.read())
    unverified_header = jwt.get_unverified_header(token)
    rsa_key = {}
    for key in jwks["keys"]:
        if key["kid"] == unverified_header["kid"]:
            rsa_key = {
                "kty": key["kty"],
                "kid": key["kid"],
                "use": key["use"],
                "n": key["n"],
                "e": key["e"]
            }
    if rsa_key:
        try:
            payload = jwt.decode(
                token,
                rsa_key,
                algorithms=["RS256"],
                audience=domain+"/api/v2/",
                issuer=domain+'/'
            )
        except jwt.ExpiredSignatureError:
            raise
        except jwt.JWTClaimsError:
            raise
        except Exception:
            raise

        return payload['sub']


# Monkey patch
auth0_component.getVerifiedSubFromToken = patchGetVerifiedSubFromToken
```

**Comment by fonnebien** [comment]
@conradbezMcK Would appreciate the approval of this PR and merge. This solves an important issue for those who want to use this component who are based outside of the US. 
Thanks in advance!

**Pull request merged**
