### PR TITLE
allow custom domain

### PR DESCRIPTION
**Pull request by amy-why**
per message thread 
https://discuss.streamlit.io/t/new-component-auth0-component-a-simple-way-to-authenticate-a-user/18260/18

### CODE REVIEW

**Comment by jannik-el** [comment]
@conradbez please approve this pull request - this makes your streamlit component which otherwise works fine, completely useless for a large part of the world :( 

EU Domains are mandatory if you are working with users from the EU due to GDPR data controller regulation.

**Comment by danissimov** [comment]
additional vote for this pull request! having a domain in the EU I am not able to use the component :(

**Comment by fonnebien** [comment]
> @conradbez please approve this pull request - this makes your streamlit component which otherwise works fine, completely useless for a large part of the world :(
> 
> EU Domains are mandatory if you are working with users from the EU due to GDPR data controller regulation.

For specific EU domains, refer to #17 and bump there. I'm having the same issue right now.

**Comment by conradbez** [comment]
EU domains should now be working :) also added @grokpot as a contributor (wrote the EU changes) as I'm very busy atm and not getting time for PR's 

Also I'll have to upload the new version to PYPI (to pip install) when I get a chance so for now it won't be on there :(

**Pull request closed without merging**
